name: Daily Contribution Commit

on:
  schedule:
    - cron: "0 4 * * *"   # 10 AM IST daily
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update log
        run: echo "Update on $(date)" >> activity-log.txt

      - name: Commit & Push as REAL USER
        run: |
          git config --global user.email "webdevpraveen@gmail.com"
          git config --global user.name "webdevpraveen"

          git add .
          git commit -m "Daily streak update $(date)" || exit 0
          git push https://webdevpraveen:${{ secrets.PAT }}@github.com/webdevpraveen/xyz.git
